language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

install:
 - export GO15VENDOREXPERIMENT=1
 - go get -u -d -t -v github.com/Masterminds/glide
 - go install github.com/Masterminds/glide
 - glide install

before_script:
  - mysql -e 'create database pop_test;'
  - mysql -u travis --password= pop_test < sql_scripts/mysql-pop_test.sql
  - psql -c 'create database pop_test;' -U postgres
  - psql pop_test < sql_scripts/postgres-pop_test.sql

# script: ./test.sh
# script: ./travis.sh
script: go test $(glide novendor)

global_env:
  - MYSQL_USER="travis"
  - MYSQL_PASSWORD=""
  - POSTGRES_PASSWORD=""

env:
  - SODA_DIALECT="postgres"
  - SODA_DIALECT="mysql_travis"
  # - SODA_DIALECT="sqlite"

addons:
  postgresql: "9.3"

matrix:
  allow_failures:
    - go: 'tip'

