mysql:
  dialect: "mysql"
  database: "pop_test"
  host: {{ envOr "MYSQL_HOST" "localhost"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  "root"  }}

mysql_travis:
  dialect: "mysql"
  database: "pop_test"
  host: {{ envOr "MYSQL_HOST" "localhost"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  ""  }}

postgres:
  dialect: "postgres"
  url: "postgres://postgres:postgres@localhost:5432/pop_test?sslmode=disable"

sqlite:
  dialect: "sqlite3"
  database: "./sql_scripts/sqlite/test.sqlite"
